name: Publish gem to Github Packages

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and publish to GitHub Package
        uses: actionshub/publish-gem-to-github@master
        with:
          token: ${{ secrets.PUBLISH_TOKEN }}
          owner: ${{ secrets.OWNER }}
